version: '3'

services:
  products:
    image: products
    deploy:
      replicas: 2
    ports:
      - 5002:3000
  frontend:
    image: frontend
    deploy:
      replicas: 2
    ports:
      - 3000:3000
  kitchen:
    image: kitchen
    deploy:
      replicas: 1
    ports:
      - 5003:3000
  auth:
    image: auth
    deploy:
      replicas: 1
    ports:
      - 5005:3000
  makeorder:
    image: makeorder
    deploy:
      replicas: 1
    ports:
      - 5004:80
    volumes:
      - ./makeorder-microservice:/var/www/html
  graph-microservice:
    image: graph-microservice
    deploy:
      replicas: 4
    ports:
      - 4000:4000
  car-microservice:
    image: car-microservice
    deploy:
      replicas: 1
    ports:
      - 5000:5000
  visualizer:
    image: dockersamples/visualizer
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
