version: '3'

services:
  products:
    image: products
    deploy:
      replicas: 2
    ports:
      - 5002:3000
  frontend:
    image: frontend
    deploy:
      replicas: 2
    ports:
      - 3000:3000
  kitchen:
    image: kitchen
    deploy:
      replicas: 1
    ports:
      - 5003:3000
  hello:
    image: hello
    deploy:
      replicas: 1
    ports:
      - 5000:3000
  papa:
    image: papa
    deploy:
      replicas: 1
    ports:
      - 5001:3000
  makeorder:
    image: makeorder
    deploy:
      replicas: 1
    ports:
      - 5004:80
    volumes:
      - ./makeorder-microservice:/var/www/html
  visualizer:
    image: dockersamples/visualizer
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
